import {
    AlertTriangle,
    ArrowDown,
    ArrowRight,
    ArrowUp,
    ArrowUpRight,
    Bell,
    BellOff,
    Calendar,
    ChartBar,
    ChartLine,
    Check,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    CircleAlert,
    CirclePlus,
    Clock,
    CreditCard,
    DollarSign,
    Download,
    Edit,
    ExternalLink,
    Eye,
    EyeOff,
    Filter,
    Folder,
    GripVertical,
    House,
    LayoutDashboard,
    LogOut,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Pause,
    PiggyBank,
    Play,
    Plus,
    Receipt,
    RefreshCw,
    Search,
    Settings,
    Sparkles,
    Sun,
    Tag,
    Trash,
    Trash2,
    TrendingDown,
    TrendingUp,
    Upload,
    UserRound,
    Wallet,
    X,
    XCircle,
    Zap,
} from "lucide-react";

export const Icons = {
    AlertCircle: CircleAlert,
    AlertTriangle,
    ArrowDown,
    ArrowRight,
    ArrowUp,
    ArrowUpRight,
    BarChart: ChartBar,
    Bell,
    BellOff,
    Calendar,
    ChartBar,
    ChartLine,
    Check,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    CircleAlert,
    CirclePlus,
    Clock,
    Close: X,
    CreditCard,
    DollarSign,
    DotsThreeVertical: MoreVertical,
    Download,
    Edit,
    ExternalLink,
    Eye,
    EyeOff,
    Filter,
    Folder,
    GripVertical,
    House,
    LayoutDashboard,
    LineChart: ChartLine,
    LogOut,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Pause,
    PencilSimple: Edit,
    PiggyBank,
    Play,
    Plus,
    PlusCircle: CirclePlus,
    Receipt,
    RefreshCw,
    Search,
    Settings,
    Sparkles,
    Sun,
    Tag,
    Trash,
    Trash2,
    TrendingDown,
    TrendingUp,
    Upload,
    User: UserRound,
    Wallet,
    X,
    XCircle,
    Zap,
};

export type IconName = keyof typeof Icons;
